version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: backend_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: backend_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend_network

  backend:
    build: .
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/backend_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - backend_network
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mongodb_data:

networks:
  backend_network:
    driver: bridge 